### ISSUE TITLE
temporary2_destination_sync

### ISSUE THREAD

**Issue by berejznoy** [swar/Swar-Chia-Plot-Manager#43]
Hello. Could you more say about temporary2_destination_sync? 
Should I use true in this field if I use temporary2_destination? 
Thank you

**Comment by swar** [comment]
`temporary2_destination_sync` - This field will always submit the destination directory as the temporary2 directory. These two directories will be in sync so that they will always be submitted as the same value.


Basically you do not have to worry about this field. It only matters to you if you want to use the same temporary2 directory as your destination directory. In this case it will sync these options by using the destination directory for both flags.

**Comment by berejznoy** [comment]
Thank you
