### ISSUE TITLE
All jobs have the same name

### ISSUE THREAD

**Issue by HorstSan** [swar/Swar-Chia-Plot-Manager#69]
Hello,

I somehow triggered a condition where all my jobs have the same name in view. All jobs are performed as expected, it's just the display name that is wrong.

The following config.yaml has this issue (please note the different file name is for uploading only, as I am too dumb to properly post code here):

[config - Kopie.yaml.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6412149/config.-.Kopie.yaml.txt)

This config.yaml leads this result:

![job1](https://user-images.githubusercontent.com/83498321/116826063-73203e80-ab92-11eb-85c3-d6f89f792339.png)

I started again from skretch and modifying the default config now shows the correct names (micron/inland as well as other names work). Although I can't really find any formatting differences/errors compared to the posted config (obviously some values differ).

[config - current.yaml.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6412155/config.-.current.yaml.txt)

**Comment by swar** [comment]
Use folders for your directory paths and have them. unique for each job. The manager is working properly as long as you haven't restarted it, but the view cannot identify the jobs properly because it uses your config to find jobs. In this case, since both use the same Temp and Destination, it cannot find the appropriate one.

**Comment by HorstSan** [comment]
Roger that. While I don't think this is an intuitive behaviour, documentation at this place in case somebody is looking for it should be good enough.
