### ISSUE TITLE
Chia processes are started with 'very low' priority on Linux

### ISSUE THREAD

**Issue by modsoft** [swar/Swar-Chia-Plot-Manager#86]
@swar  thanks again for this awesome manager :)
I have noticed that the chia plotting processes are created with 'Very Low' priority. while processes created through the Chia GUI are normal priority. 
Is there a way to spawn them at High or Very High priority? Will this have an effect on performance and phase completion time?

Thanks,
![image](https://user-images.githubusercontent.com/1141446/116964852-59016180-ac61-11eb-9875-498d29940135.png)

**Comment by spacewaffles309** [comment]
You seem to have the opposite situation that I and another member had, mentioned here

https://github.com/swar/Swar-Chia-Plot-Manager/issues/52

So a similar 'reverse tweak' might work for you.  Or, it looks like the default for the project has been set to Normal priority as of a few hours ago, so updating to the newest releases might clear it up for you.

On the question about the impact it could have, in my situation lowering it actually improved my daily finishes, because the extreme high priority made my systems so fragile that they'd fall on their face if you even looked in their general direction.  The Normal priority has been working great for me.

**Comment by Amdaxiom** [comment]
@modsoft Is there any particular reason you would want high or very high priority? Linux is very good at handing out resources as and will automatically use up to 100% of available resources. High priority can end up starving system processes and make the system unstable as @spacewaffles309 points out and will slow down your actual plotting speeds. I wouldn't want very low but I would want normal priority as my preference.

**Comment by swar** [comment]
@modsoft This is where you would change that value for yourself: https://github.com/swar/Swar-Chia-Plot-Manager/blob/main/plotmanager/library/utilities/jobs.py#L129

nice_val is the value you want to change, but I do not know the best value for Linux.

To be honest, I have a plan to get custom priority levels per jobs added in, but I had a busy weekend and I've been absolutely swamped with how much this library has taken off. In turn, it's just caused me to take a small break from this plotter. This is a higher priority on my roadmap on completing.

**Comment by stubmirror** [comment]
my nice val is at 10, wich makes it very low in ubuntu, i didnt notice until i came over this post by accident it was def hurting performance, set it to 0 for normal priority, should probabaly be normal by defualt?

**Comment by swar** [comment]
Added in the development branch for customization.

**Comment by swar** [comment]
> my nice val is at 10, wich makes it very low in ubuntu, i didnt notice until i came over this post by accident it was def hurting performance, set it to 0 for normal priority, should probabaly be normal by defualt?

You can make a case for being higher or lower or staying the same. It depends on what the user is doing with their PC.
